# Generated by Django 3.1 on 2020-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='', upload_to='MyWeb/images'),
        ),
    ]
