# Generated by Django 3.1 on 2020-08-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0002_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField(default='my name is <django.db.models.fields.CharField>')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
