# Generated by Django 3.1 on 2020-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0003_auto_20200828_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc1', models.CharField(max_length=100)),
                ('dsc2', models.CharField(max_length=100)),
                ('dsc3', models.CharField(max_length=100)),
                ('dsc4', models.CharField(max_length=100)),
                ('dsc5', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=50)),
                ('telegramId', models.CharField(max_length=50)),
                ('resume', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
