# Generated by Django 3.1 on 2020-08-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWeb', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability1', models.CharField(default='', max_length=50)),
                ('abil1_percent', models.IntegerField(default=0)),
                ('ability2', models.CharField(default='', max_length=50)),
                ('abil2_percent', models.IntegerField(default=0)),
                ('ability3', models.CharField(default='', max_length=50)),
                ('abil3_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
